#!/bin/bash
echo ""
echo " Copying udev rules..."
echo ""
sudo cp `rospack find schunk_svh_driver`/udev/99-brainboxes-us.rules /etc/udev/rules.d
echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart
